linters:
  enable-all: true
  disable:
    # Disable deprecated linters.
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # Depguard makes more sense for larger projects.
    - depguard
linters-settings:
  ireturn:
    allow:
      - error
      - meganruggiero\.com/dicebot/internal/ast\.Term
